--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Outubro-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_AM_CLA_BAIRRO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_BAIRRO" 
   (	"ID_BAIRRO" NUMBER(5,0), 
	"ID_CIDADE" NUMBER(5,0), 
	"NM_BAIRRO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_CLIENTE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" 
   (	"ID_CLIENTE" NUMBER(5,0), 
	"NR_CPF" NUMBER(11,0), 
	"NR_RG" NUMBER(11,0), 
	"DT_NASCIMENTO" DATE, 
	"NR_QUARTO_PREFERIDO" NUMBER(2,0), 
	"DS_EMAIL" VARCHAR2(60 BYTE), 
	"DS_SENHA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_RESERVA
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" 
   (	"ID_RESERVA" NUMBER(8,0), 
	"ID_CLIENTE" NUMBER(5,0), 
	"ID_FUNCIONARIO" NUMBER(5,0), 
	"DT_SOLICITACAO" DATE, 
	"DT_INICIO_RESERVA" DATE, 
	"DT_FINAL_RESERVA" DATE, 
	"QT_ADULTO" NUMBER(1,0), 
	"QT_CRIANCA" NUMBER(1,0), 
	"ST_RESERVA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PAGAMENTO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" 
   (	"ID_HOSPEDAGEM" NUMBER(5,0), 
	"ID_TIPO_FORMAPAG" NUMBER(5,0), 
	"VL_PAGAMENTO" NUMBER(8,2), 
	"DT_PAGAMENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_ESTADO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_ESTADO" 
   (	"ID_ESTADO" NUMBER(2,0), 
	"NM_ESTADO" CHAR(20 BYTE), 
	"SG_ESTADO" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_FUNCIONARIO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" 
   (	"ID_FUNCIONARIO" NUMBER(5,0), 
	"DT_ADMISSAO" DATE, 
	"DS_CARGO" NUMBER(1,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"SENHA" VARCHAR2(20 BYTE), 
	"NOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PRODUTO_SERVICO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" 
   (	"ID_TIPO_SERVICO" NUMBER(5,0), 
	"DS_SERVICO" VARCHAR2(40 BYTE), 
	"NR_TIPO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_HIST_PRECO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" 
   (	"ID_HIST_PRECO" NUMBER(8,0), 
	"ID_TIPO_SERVICO" NUMBER(5,0), 
	"DT_VALIDADE" DATE, 
	"VL_PRECO" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_TELEFONE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" 
   (	"ID_FONE" NUMBER(8,0), 
	"ID_TIPO_FONE" NUMBER(2,0), 
	"NR_DDD" NUMBER(3,0), 
	"NR_TELEFONE" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PAG_CHEQUE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" 
   (	"ID_PAGTO_CHEQUE" NUMBER(6,0), 
	"ID_HOSPEDAGEM" NUMBER(8,0), 
	"NR_BANCO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_HOSPEDAGEM
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" 
   (	"ID_HOSPEDAGEM" NUMBER(8,0), 
	"NR_QUARTO" NUMBER(4,0), 
	"ID_RESERVA" NUMBER(8,0), 
	"ID_CLIENTE" NUMBER(5,0), 
	"ID_FUNCIONARIO" NUMBER(5,0), 
	"VL_PERC_DESCONTO" NUMBER(5,2), 
	"DT_ENTRADA" DATE, 
	"DT_SAIDA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_TIPO_LOG
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_TIPO_LOG" 
   (	"ID_TIPO_LOGRADOURO" NUMBER(2,0), 
	"DS_TIPO_LOGRADOURO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_CONSUMO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" 
   (	"ID_CONSUMO" NUMBER(8,0), 
	"ID_HOSPEDAGEM" NUMBER(8,0), 
	"ID_TIPO_SERVICO" NUMBER(5,0), 
	"ID_FUNCIONARIO" NUMBER(5,0), 
	"DT_CONSUMO" DATE, 
	"QT_CONSUMIDA" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_LOGRADOURO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" 
   (	"NR_CEP" NUMBER(8,0), 
	"ID_BAIRRO" NUMBER(5,0), 
	"ID_TIPO_LOGRADOURO" NUMBER(2,0), 
	"DS_LOGRADOURO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_HIST_VALOR
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_HIST_VALOR" 
   (	"ID_HISTORICO" NUMBER(6,0), 
	"DT_VALIDADE" DATE, 
	"VL_PRECO_QUARTO" NUMBER(6,2), 
	"ID_TIPO_QUARTO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_TIPO_FORMAPAG
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" 
   (	"ID_TIPO_FORMAPAG" NUMBER(1,0), 
	"DS_FORMAPAG" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_TIPO_FONE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FONE" 
   (	"ID_TIPO_FONE" NUMBER(2,0), 
	"DS_TIPO_FONE" CHAR(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_RESERVA_QUARTO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" 
   (	"NR_QUARTO" NUMBER(8,0), 
	"ID_RESERVA" NUMBER(5,0), 
	"QT_PESSOA_QUARTO" NUMBER(1,0), 
	"DS_OBSERVACAO" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PESSOA
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PESSOA" 
   (	"ID_PESSOA" NUMBER(5,0), 
	"NM_PESSOA" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_REL_CHEQUE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" 
   (	"ID_HOSPEDAGEM" NUMBER(5,0), 
	"ID_PAGTO_CHEQUE" NUMBER(5,0), 
	"NR_CHEQUE" NUMBER(5,0), 
	"VL_PARCELA" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_QUARTO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" 
   (	"NR_QUARTO" NUMBER(4,0), 
	"ID_TIPO_QUARTO" NUMBER(2,0), 
	"NR_ANDAR" NUMBER(2,0), 
	"NR_CAPACIDADE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PESSOA_FONE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" 
   (	"ID_FONE" NUMBER(8,0), 
	"ID_PESSOA" NUMBER(5,0), 
	"NR_RAMAL" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_TIPO_QUARTO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" 
   (	"ID_TIPO_QUARTO" NUMBER(2,0), 
	"DS_TIPO_QUARTO" VARCHAR2(25 BYTE), 
	"DS_OBSERVACAO" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PAGCARTAO
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PAGCARTAO" 
   (	"ID_PAGTO_CARTAO" NUMBER(6,0), 
	"ID_HOSPEDAGEM" NUMBER(8,0), 
	"QT_PARCELA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_CIDADE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_CIDADE" 
   (	"ID_CIDADE" NUMBER(5,0), 
	"ID_ESTADO" NUMBER(2,0), 
	"NM_CIDADE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_AM_CLA_PESSOA_ENDE
--------------------------------------------------------

  CREATE TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" 
   (	"ID_PESSOA_ENDE" NUMBER(8,0), 
	"NR_CEP" NUMBER(8,0), 
	"NR_LOGRADOURO" NUMBER(5,0), 
	"ID_PESSOA" NUMBER(5,0), 
	"DS_COMPLEMENTO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_BAIRRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_BAIRRO" ON "OPS$RM74694"."T_AM_CLA_BAIRRO" ("ID_BAIRRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_CLIENTE" ON "OPS$RM74694"."T_AM_CLA_CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_CLA_CLIENTE_CPF
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_CLA_CLIENTE_CPF" ON "OPS$RM74694"."T_AM_CLA_CLIENTE" ("NR_CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_CLA_CLIENTE_RG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_CLA_CLIENTE_RG" ON "OPS$RM74694"."T_AM_CLA_CLIENTE" ("NR_RG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_CLA_CLIENTE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_CLA_CLIENTE_EMAIL" ON "OPS$RM74694"."T_AM_CLA_CLIENTE" ("DS_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_RESERVA
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_RESERVA" ON "OPS$RM74694"."T_AM_CLA_RESERVA" ("ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_FORMA_PAGAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_FORMA_PAGAMENTO" ON "OPS$RM74694"."T_AM_CLA_PAGAMENTO" ("ID_HOSPEDAGEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_ESTADO" ON "OPS$RM74694"."T_AM_CLA_ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_FUNCIONARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_FUNCIONARIO" ON "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" ("ID_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_PRODUTO_SERVICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_PRODUTO_SERVICO" ON "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" ("ID_TIPO_SERVICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_CLA_PROD_SERV_DESC
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_CLA_PROD_SERV_DESC" ON "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" ("DS_SERVICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_HIST_PRECO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_HIST_PRECO" ON "OPS$RM74694"."T_AM_CLA_HIST_PRECO" ("ID_HIST_PRECO", "ID_TIPO_SERVICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_TELEFONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_TELEFONE" ON "OPS$RM74694"."T_AM_CLA_TELEFONE" ("ID_FONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_PAG_CHEQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_PAG_CHEQUE" ON "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" ("ID_PAGTO_CHEQUE", "ID_HOSPEDAGEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_HOSPEDAGEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_HOSPEDAGEM" ON "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ("ID_HOSPEDAGEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_AM_CLA_HOSPEDAGEM_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM_UQ" ON "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ("ID_RESERVA", "NR_QUARTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_TIPO_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_TIPO_LOG" ON "OPS$RM74694"."T_AM_CLA_TIPO_LOG" ("ID_TIPO_LOGRADOURO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_CLA_TIPO_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_CLA_TIPO_LOG" ON "OPS$RM74694"."T_AM_CLA_TIPO_LOG" ("DS_TIPO_LOGRADOURO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_REGISTRO_CONSUMO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_REGISTRO_CONSUMO" ON "OPS$RM74694"."T_AM_CLA_CONSUMO" ("ID_CONSUMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_LOGRADOURO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_LOGRADOURO" ON "OPS$RM74694"."T_AM_CLA_LOGRADOURO" ("NR_CEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_HIST_VALOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_HIST_VALOR" ON "OPS$RM74694"."T_AM_CLA_HIST_VALOR" ("ID_HISTORICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_TIPO_FORMAPAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_TIPO_FORMAPAG" ON "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" ("ID_TIPO_FORMAPAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_CLA_TIPO_FORMAPAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_CLA_TIPO_FORMAPAG" ON "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" ("DS_FORMAPAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_TIPO_FONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_TIPO_FONE" ON "OPS$RM74694"."T_AM_CLA_TIPO_FONE" ("ID_TIPO_FONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UN_AM_HBV_TIPO_FONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."UN_AM_HBV_TIPO_FONE" ON "OPS$RM74694"."T_AM_CLA_TIPO_FONE" ("DS_TIPO_FONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_RESERVA_QUARTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_RESERVA_QUARTO" ON "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" ("NR_QUARTO", "ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_PESSOA
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_PESSOA" ON "OPS$RM74694"."T_AM_CLA_PESSOA" ("ID_PESSOA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_REL_CHEQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_REL_CHEQUE" ON "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" ("ID_PAGTO_CHEQUE", "ID_HOSPEDAGEM", "NR_CHEQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_QUARTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_QUARTO" ON "OPS$RM74694"."T_AM_CLA_QUARTO" ("NR_QUARTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_PESSOA_FONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_PESSOA_FONE" ON "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" ("ID_FONE", "ID_PESSOA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_TIPO_QUARTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_TIPO_QUARTO" ON "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" ("ID_TIPO_QUARTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_PAGCARTAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_PAGCARTAO" ON "OPS$RM74694"."T_AM_CLA_PAGCARTAO" ("ID_PAGTO_CARTAO", "ID_HOSPEDAGEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_HBV_CIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_HBV_CIDADE" ON "OPS$RM74694"."T_AM_CLA_CIDADE" ("ID_CIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_AM_CLA_PESSOA_ENDE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPS$RM74694"."PK_AM_CLA_PESSOA_ENDE" ON "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" ("ID_PESSOA_ENDE", "NR_CEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_BAIRRO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_BAIRRO" ADD CONSTRAINT "PK_AM_CLA_BAIRRO" PRIMARY KEY ("ID_BAIRRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_BAIRRO" MODIFY ("ID_BAIRRO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_BAIRRO" MODIFY ("ID_CIDADE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_BAIRRO" MODIFY ("NM_BAIRRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_CLIENTE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" ADD CONSTRAINT "PK_AM_CLA_CLIENTE" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" MODIFY ("NR_CPF" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" MODIFY ("NR_RG" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" MODIFY ("DT_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" MODIFY ("DS_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" MODIFY ("DS_SENHA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" ADD CONSTRAINT "UN_AM_CLA_CLIENTE_CPF" UNIQUE ("NR_CPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" ADD CONSTRAINT "UN_AM_CLA_CLIENTE_EMAIL" UNIQUE ("DS_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" ADD CONSTRAINT "UN_AM_CLA_CLIENTE_RG" UNIQUE ("NR_RG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_RESERVA
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" ADD CONSTRAINT "PK_AM_CLA_RESERVA" PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("DT_SOLICITACAO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("DT_INICIO_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("DT_FINAL_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("QT_ADULTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("QT_CRIANCA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" MODIFY ("ST_RESERVA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PAGAMENTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" ADD CONSTRAINT "PK_AM_CLA_FORMA_PAGAMENTO" PRIMARY KEY ("ID_HOSPEDAGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" MODIFY ("ID_HOSPEDAGEM" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" MODIFY ("ID_TIPO_FORMAPAG" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" MODIFY ("VL_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" MODIFY ("DT_PAGAMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_ESTADO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_ESTADO" ADD CONSTRAINT "PK_AM_HBV_ESTADO" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_ESTADO" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_ESTADO" MODIFY ("NM_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_ESTADO" MODIFY ("SG_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" ADD CONSTRAINT "PK_AM_CLA_FUNCIONARIO" PRIMARY KEY ("ID_FUNCIONARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" MODIFY ("DT_ADMISSAO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" MODIFY ("DS_CARGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PRODUTO_SERVICO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" ADD CONSTRAINT "PK_AM_HBV_PRODUTO_SERVICO" PRIMARY KEY ("ID_TIPO_SERVICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" MODIFY ("ID_TIPO_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" MODIFY ("DS_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" MODIFY ("NR_TIPO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" ADD CONSTRAINT "UN_AM_CLA_PROD_SERV_DESC" UNIQUE ("DS_SERVICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_HIST_PRECO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" ADD CONSTRAINT "PK_AM_CLA_HIST_PRECO" PRIMARY KEY ("ID_HIST_PRECO", "ID_TIPO_SERVICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" MODIFY ("ID_HIST_PRECO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" MODIFY ("ID_TIPO_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" MODIFY ("DT_VALIDADE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" MODIFY ("VL_PRECO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_TELEFONE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" ADD CONSTRAINT "PK_AM_HBV_TELEFONE" PRIMARY KEY ("ID_FONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" MODIFY ("ID_FONE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" MODIFY ("ID_TIPO_FONE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" MODIFY ("NR_DDD" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" MODIFY ("NR_TELEFONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PAG_CHEQUE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" ADD CONSTRAINT "PK_AM_CLA_PAG_CHEQUE" PRIMARY KEY ("ID_PAGTO_CHEQUE", "ID_HOSPEDAGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" MODIFY ("ID_PAGTO_CHEQUE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" MODIFY ("ID_HOSPEDAGEM" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" MODIFY ("NR_BANCO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_HOSPEDAGEM
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ADD CONSTRAINT "PK_AM_CLA_HOSPEDAGEM" PRIMARY KEY ("ID_HOSPEDAGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("ID_HOSPEDAGEM" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("NR_QUARTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("VL_PERC_DESCONTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" MODIFY ("DT_ENTRADA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ADD CONSTRAINT "T_AM_CLA_HOSPEDAGEM_UQ" UNIQUE ("ID_RESERVA", "NR_QUARTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_TIPO_LOG
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_LOG" ADD CONSTRAINT "PK_AM_CLA_TIPO_LOG" PRIMARY KEY ("ID_TIPO_LOGRADOURO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_LOG" MODIFY ("ID_TIPO_LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_LOG" MODIFY ("DS_TIPO_LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_LOG" ADD CONSTRAINT "UN_AM_CLA_TIPO_LOG" UNIQUE ("DS_TIPO_LOGRADOURO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_CONSUMO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" ADD CONSTRAINT "PK_AM_HBV_REGISTRO_CONSUMO" PRIMARY KEY ("ID_CONSUMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" MODIFY ("ID_CONSUMO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" MODIFY ("ID_HOSPEDAGEM" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" MODIFY ("ID_TIPO_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" MODIFY ("DT_CONSUMO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" MODIFY ("QT_CONSUMIDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_LOGRADOURO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" ADD CONSTRAINT "PK_AM_HBV_LOGRADOURO" PRIMARY KEY ("NR_CEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" MODIFY ("NR_CEP" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" MODIFY ("ID_BAIRRO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" MODIFY ("ID_TIPO_LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" MODIFY ("DS_LOGRADOURO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_HIST_VALOR
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_VALOR" ADD CONSTRAINT "PK_AM_CLA_HIST_VALOR" PRIMARY KEY ("ID_HISTORICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_VALOR" MODIFY ("ID_HISTORICO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_VALOR" MODIFY ("DT_VALIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_TIPO_FORMAPAG
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" ADD CONSTRAINT "PK_AM_CLA_TIPO_FORMAPAG" PRIMARY KEY ("ID_TIPO_FORMAPAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" MODIFY ("ID_TIPO_FORMAPAG" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" MODIFY ("DS_FORMAPAG" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" ADD CONSTRAINT "UN_AM_CLA_TIPO_FORMAPAG" UNIQUE ("DS_FORMAPAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_TIPO_FONE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FONE" ADD CONSTRAINT "PK_AM_HBV_TIPO_FONE" PRIMARY KEY ("ID_TIPO_FONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FONE" MODIFY ("ID_TIPO_FONE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FONE" MODIFY ("DS_TIPO_FONE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_FONE" ADD CONSTRAINT "UN_AM_HBV_TIPO_FONE" UNIQUE ("DS_TIPO_FONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_RESERVA_QUARTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" ADD CONSTRAINT "PK_AM_CLA_RESERVA_QUARTO" PRIMARY KEY ("NR_QUARTO", "ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" MODIFY ("NR_QUARTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" MODIFY ("QT_PESSOA_QUARTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PESSOA
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA" ADD CONSTRAINT "PK_AM_CLA_PESSOA" PRIMARY KEY ("ID_PESSOA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA" MODIFY ("NM_PESSOA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_REL_CHEQUE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" ADD CONSTRAINT "PK_AM_CLA_REL_CHEQUE" PRIMARY KEY ("ID_PAGTO_CHEQUE", "ID_HOSPEDAGEM", "NR_CHEQUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" MODIFY ("ID_HOSPEDAGEM" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" MODIFY ("ID_PAGTO_CHEQUE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" MODIFY ("NR_CHEQUE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" MODIFY ("VL_PARCELA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_QUARTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" ADD CONSTRAINT "PK_AM_HBV_QUARTO" PRIMARY KEY ("NR_QUARTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" MODIFY ("NR_QUARTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" MODIFY ("ID_TIPO_QUARTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" MODIFY ("NR_ANDAR" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" MODIFY ("NR_CAPACIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PESSOA_FONE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" ADD CONSTRAINT "PK_AM_HBV_PESSOA_FONE" PRIMARY KEY ("ID_FONE", "ID_PESSOA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" MODIFY ("ID_FONE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_TIPO_QUARTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" ADD CONSTRAINT "PK_AM_CLA_TIPO_QUARTO" PRIMARY KEY ("ID_TIPO_QUARTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" MODIFY ("ID_TIPO_QUARTO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" MODIFY ("DS_TIPO_QUARTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PAGCARTAO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGCARTAO" ADD CONSTRAINT "PK_AM_CLA_PAGCARTAO" PRIMARY KEY ("ID_PAGTO_CARTAO", "ID_HOSPEDAGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGCARTAO" MODIFY ("ID_PAGTO_CARTAO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGCARTAO" MODIFY ("ID_HOSPEDAGEM" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGCARTAO" MODIFY ("QT_PARCELA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_CIDADE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CIDADE" ADD CONSTRAINT "PK_AM_HBV_CIDADE" PRIMARY KEY ("ID_CIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CIDADE" MODIFY ("ID_CIDADE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CIDADE" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CIDADE" MODIFY ("NM_CIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AM_CLA_PESSOA_ENDE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" ADD CONSTRAINT "PK_AM_CLA_PESSOA_ENDE" PRIMARY KEY ("ID_PESSOA_ENDE", "NR_CEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" MODIFY ("ID_PESSOA_ENDE" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" MODIFY ("NR_CEP" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" MODIFY ("NR_LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_BAIRRO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_BAIRRO" ADD CONSTRAINT "FK_AM_CLA_BAIRRO_CIDADE" FOREIGN KEY ("ID_CIDADE")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_CIDADE" ("ID_CIDADE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_CLIENTE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CLIENTE" ADD CONSTRAINT "FK_AM_CLA_CLIENTE_PESSOA" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_RESERVA
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" ADD CONSTRAINT "FK_AM_CLA_RESERVA_CLIENTE" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA" ADD CONSTRAINT "FK_AM_CLA_RESERVA_FUNC" FOREIGN KEY ("ID_FUNCIONARIO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" ("ID_FUNCIONARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_PAGAMENTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" ADD CONSTRAINT "FK_AM_CLA_PAGTO_HOSPEDAGEM" FOREIGN KEY ("ID_HOSPEDAGEM")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ("ID_HOSPEDAGEM") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGAMENTO" ADD CONSTRAINT "FK_AM_CLA_PAGTO_TIPO_FORMAPAG" FOREIGN KEY ("ID_TIPO_FORMAPAG")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_TIPO_FORMAPAG" ("ID_TIPO_FORMAPAG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" ADD CONSTRAINT "FK_AM_CLA_FUNC_PESSOA" FOREIGN KEY ("ID_FUNCIONARIO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_HIST_PRECO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_PRECO" ADD CONSTRAINT "FK_AM_CLA_HISTPRECO_PROD_SERV" FOREIGN KEY ("ID_TIPO_SERVICO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" ("ID_TIPO_SERVICO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_TELEFONE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_TELEFONE" ADD CONSTRAINT "PK_AM_HBV_FONE_TIPO_FONE" FOREIGN KEY ("ID_TIPO_FONE")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_TIPO_FONE" ("ID_TIPO_FONE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_PAG_CHEQUE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" ADD CONSTRAINT "FK_AM_CLA_PAG_CHEQUE_PAGATO" FOREIGN KEY ("ID_HOSPEDAGEM")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PAGAMENTO" ("ID_HOSPEDAGEM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_HOSPEDAGEM
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ADD CONSTRAINT "FK_AM_CLA_HOSPEDAGEM_CLIENTE" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ADD CONSTRAINT "FK_AM_CLA_HOSPEDAGEM_FUNC" FOREIGN KEY ("ID_FUNCIONARIO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" ("ID_FUNCIONARIO") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ADD CONSTRAINT "FK_AM_CLA_HOSP_RESERVAQTO" FOREIGN KEY ("NR_QUARTO", "ID_RESERVA")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" ("NR_QUARTO", "ID_RESERVA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_CONSUMO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" ADD CONSTRAINT "FK_AM_CLA_CONSUMO_HOSPEDAGEM" FOREIGN KEY ("ID_HOSPEDAGEM")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_HOSPEDAGEM" ("ID_HOSPEDAGEM") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" ADD CONSTRAINT "FK_AM_CLA_CONSUMO_PROD_SERV" FOREIGN KEY ("ID_TIPO_SERVICO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PRODUTO_SERVICO" ("ID_TIPO_SERVICO") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CONSUMO" ADD CONSTRAINT "FK_AM_CONSUMO_FUNCIONARIO" FOREIGN KEY ("ID_FUNCIONARIO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_FUNCIONARIO" ("ID_FUNCIONARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_LOGRADOURO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" ADD CONSTRAINT "FK_AM_CLA_LOGRADOURO_BAIRRO" FOREIGN KEY ("ID_BAIRRO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_BAIRRO" ("ID_BAIRRO") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_LOGRADOURO" ADD CONSTRAINT "FK_AM_CLA_LOGRADOURO_TIPO_LOG" FOREIGN KEY ("ID_TIPO_LOGRADOURO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_TIPO_LOG" ("ID_TIPO_LOGRADOURO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_HIST_VALOR
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_HIST_VALOR" ADD CONSTRAINT "FK_AM_CLA_HISTVALOR_TIPOQUARTO" FOREIGN KEY ("ID_TIPO_QUARTO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" ("ID_TIPO_QUARTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_RESERVA_QUARTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" ADD CONSTRAINT "FK_AM_CLA_RESERVAQTO_QUARTO" FOREIGN KEY ("NR_QUARTO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_QUARTO" ("NR_QUARTO") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_RESERVA_QUARTO" ADD CONSTRAINT "FK_AM_CLA_RESERVAQTO_RESERVA" FOREIGN KEY ("ID_RESERVA")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_RESERVA" ("ID_RESERVA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_REL_CHEQUE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_REL_CHEQUE" ADD CONSTRAINT "PK_AM_CLA_RELCHEQUE_PAGCHEQUE" FOREIGN KEY ("ID_PAGTO_CHEQUE", "ID_HOSPEDAGEM")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PAG_CHEQUE" ("ID_PAGTO_CHEQUE", "ID_HOSPEDAGEM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_QUARTO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_QUARTO" ADD CONSTRAINT "FK_AM_CLA_TIPO_QUARTO" FOREIGN KEY ("ID_TIPO_QUARTO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_TIPO_QUARTO" ("ID_TIPO_QUARTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_PESSOA_FONE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" ADD CONSTRAINT "FK_AM_CLA_PESSOA_FONE_FONE" FOREIGN KEY ("ID_FONE")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_TELEFONE" ("ID_FONE") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_FONE" ADD CONSTRAINT "FK_AM_HBV_PESSOA_FONE_PESSOA" FOREIGN KEY ("ID_PESSOA")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_PAGCARTAO
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PAGCARTAO" ADD CONSTRAINT "FK_AM_CLA_PAGCARTAO" FOREIGN KEY ("ID_HOSPEDAGEM")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PAGAMENTO" ("ID_HOSPEDAGEM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_CIDADE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_CIDADE" ADD CONSTRAINT "FK_AM_CLA_CIDADE_ESTADO" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_ESTADO" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_AM_CLA_PESSOA_ENDE
--------------------------------------------------------

  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" ADD CONSTRAINT "PK_AM_CLA_PESSOA_ENDE_LOG" FOREIGN KEY ("NR_CEP")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_LOGRADOURO" ("NR_CEP") ENABLE;
  ALTER TABLE "OPS$RM74694"."T_AM_CLA_PESSOA_ENDE" ADD CONSTRAINT "PK_AM_CLA_PESSOA_ENDE_PESSOA" FOREIGN KEY ("ID_PESSOA")
	  REFERENCES "OPS$RM74694"."T_AM_CLA_PESSOA" ("ID_PESSOA") ENABLE;
